name: 'ggml_library'
description: 'GGML Is Library machine learning in dart with special feature speed up inference model in cpu only or any gpu'
version: '0.0.10'
homepage: 'https://www.youtube.com/@general_dev'
repository: 'https://github.com/General-Developer/ggml_library'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
topics:
  - 'ggml'
  - 'artificial-intelligence'
  - 'machine-learning'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  general_lib: '^0.0.71'
  ffi: '^2.1.4'
  crypto: '^3.0.3'
  path: '^1.9.0'
  ffi_universe: '^0.0.8'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  ffigen: '^17.0.0'
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
flutter:
  uses-material-design: true
ffigen:
  name: 'GgmlLibrarySharedBindingsByGeneralDeveloper'
  description: 'GeneralAiSpeechToTextLibraryWhisper Binding By General Corporation & Global Corporation & General Developer'
  output: 'lib/core/ggml/ffi/bindings.dart'
  headers:
    entry-points:
      - '../../native_lib/lib/ggml/include/ggml.h'
      - '../../native_lib/lib/ggml/include/ggml-cpu.h'
      - '../../native_lib/lib/ggml/include/ggml-backend.h'
  compiler-opts:
    - '-I/usr/lib/clang/19.1.7/include'
  comments:
    style: 'any'
    length: 'full'
project:
  type: ''
